language: common-lisp
sudo: false

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre
env:
 global:
   - PATH=~/.roswell/bin:$PATH
#    - ROSWELL_BRANCH=master

    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl
    # - LISP=ecl
    # - LISP=allegro
    # - LISP=ccl
    # - LISP=clisp
    # does not work because cl-info fails under ABCL
    # - LISP=abcl
    # under cmucl cl-info does not work either, but for different reason
    # - LISP=cmucl

matrix:
  allow_failures:
    # 10 of 26 tests failed
    - env: LISP=clisp

os:
#  - osx
  - linux

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install asdf
  - ros install rove
  - ros install 40ants/cl-info
  - ros install 40ants/cl-hamcrest

before_script:
  - ros --version
  - ros config
  - cl-info

script:
  - rove html2text-test.asd
